_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "models/swin_base_patch4_window7_224_22k.pkl"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: B-22k
  FPN:
    IN_FEATURES: ["swin0", "swin1", "swin2", "swin3" ]
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("stenosis_train_1",)
  TEST:  ("stenosis_test_1",)
SOLVER:
  IMS_PER_BATCH: 1
  STEPS: (15000, 22000)
  MAX_ITER: 30000
SEED: 1121
INPUT:
  MIN_SIZE_TRAIN: (512,)
  MIN_SIZE_TEST: 512
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (512, 512)
  FORMAT: "L" #灰度图像，故为L
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR:
  # "./output/0630_swinB"
  "./output/code_test"