# /*
#  * Filename: /home/xinyul/python_exercises/3D_diffusuionDet/configs/diffdet.coco.res50 copy 2.yaml
#  * Path: /home/xinyul/python_exercises/3D_diffusuionDet/configs
#  * Created Date: Wednesday, November 8th 2023, 10:54:59 am
#  * Author: Xinyu Li
#  * 
#  * Copyright (c) 2023 Beijing Institude of Technology.
#  */



_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  # WEIGHTS: "./output/diffusionDet_8bit_ela_6/model_0449999.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 1
    IS_LESION: True
    NOISE: 'normal'
    REF_NUM: 4
    ADAPTIVE_WINDOW: False
    # ADAPTIVE_WINDOW: False
DATASETS:
  TRAIN: ("lesion_all_train",)
  # TEST:  ("deeplesion_val",)
  TEST:  ("lesion_all_test",)
SOLVER:
  IMS_PER_BATCH: 1
  STEPS: (350000, 420000)
  MAX_ITER: 900000
  CHECKPOINT_PERIOD: 20000
SEED: 1121
INPUT:
  MIN_SIZE_TRAIN: (512,)
  MIN_SIZE_TEST: 512
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (512, 512)
  FORMAT: "L" #灰度图像，故为L
TEST:
  EVAL_PERIOD: 50000
OUTPUT_DIR:
  "./output/diffusionDet_all_ela/"
  # "./output/diffusionDet_8bit_ela_6/test_lnq/"